/// Flutter icons Collaction
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Collaction
///      fonts:
///       - asset: fonts/Collaction.ttf
///
///
///
import 'package:flutter/widgets.dart';

class CollactionIcons {
  CollactionIcons._();

  static const _kFontFam = 'CollactionIcons';

  static const IconData eye = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData logout = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData phone = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData badge = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData down = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData cross = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData crowdaction = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData arrowRight = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData checkCircle = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData file = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData infoCircle = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData upload = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData plus = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData check = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData eyeOff = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData externalLink = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData commitment = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData question = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData lock = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData collaction = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData userPlus = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData left = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData message = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData opensource = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData crossCircle = IconData(0xe81b, fontFamily: _kFontFam);
}
