/// Flutter icons Collaction
/// Copyright (C) 2022 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  Collaction
///      fonts:
///       - asset: fonts/Collaction.ttf
///
///
///
// ignore_for_file: constant_identifier_names
import 'package:flutter/widgets.dart';

class CollactionIcons {
  const CollactionIcons._();

  static const _kFontFam = 'CollactionIcons';

  static const IconData eye = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData logout = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData phone = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData badge = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData down = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData cross = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData crowdaction = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData arrow_right = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData check_circle = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData file = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData info_circle = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData upload = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData plus = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData check = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData settings = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData eye_off = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData external_link = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData commitment = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData question = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData lock = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData collaction = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData user_plus = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData left = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData message = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData opensource = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData cross_circle = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData instagram = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData globe = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData linkedin = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData five_out_of_seven =
      IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData no_beef = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData no_cheese = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData no_dairy = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData pescatarian = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData vegan = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData vegetarian = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData crowd = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData goal = IconData(0xe827, fontFamily: _kFontFam);
}
