const invalidEmail = 'akdjsfhcaksd';
const validEmail = 'test@test.com';
const emptyUsername = '';
const shortUsername = 'abc';
const longUsername = 'abcdefghijklmnopqrstuvwxyz';
const invalidUsername = '\$1234';
const validUsername = 'collaction';
const invalidPhone = '256778914357';
const validPhone = '256 778914357';
